# Generated by Django 3.1.5 on 2021-06-23 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_cam', models.CharField(max_length=100)),
                ('primary_cam_features', models.TextField()),
                ('secondary_cam', models.CharField(max_length=100)),
                ('secondary_cam_features', models.TextField()),
                ('flash', models.CharField(max_length=50)),
                ('video_rec_resolution', models.TextField()),
                ('frame_rate', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Display',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_dimension', models.CharField(max_length=50)),
                ('resolution', models.CharField(max_length=50)),
                ('gpu', models.CharField(max_length=50)),
                ('graphics_ppi', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.ImageField(upload_to='static/Images')),
                ('img2', models.ImageField(upload_to='static/Images')),
                ('img3', models.ImageField(blank=True, upload_to='static/Images')),
                ('img4', models.ImageField(blank=True, upload_to='static/Images')),
                ('img5', models.ImageField(blank=True, upload_to='static/Images')),
                ('img6', models.ImageField(blank=True, upload_to='static/Images')),
            ],
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_memory', models.CharField(max_length=20)),
                ('ram', models.CharField(max_length=50)),
                ('expandable_storage', models.CharField(max_length=50)),
                ('microsd', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=50)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.category')),
            ],
        ),
        migrations.CreateModel(
            name='Processor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os', models.CharField(max_length=50)),
                ('processor', models.CharField(max_length=100)),
                ('clock_speed', models.CharField(max_length=100)),
                ('processor_core', models.CharField(max_length=50)),
                ('subcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='OtherDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('touchscreen_type', models.CharField(max_length=50)),
                ('sim_count', models.CharField(blank=True, max_length=30, null=True)),
                ('sim_size', models.CharField(max_length=50)),
                ('ui', models.CharField(max_length=50)),
                ('sensors', models.CharField(max_length=200)),
                ('gps_type', models.CharField(blank=True, max_length=100)),
                ('fingerprint', models.CharField(blank=True, max_length=10)),
                ('fingerprint_type', models.CharField(blank=True, max_length=50)),
                ('call_recording', models.CharField(blank=True, max_length=10)),
                ('subcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('model_no', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('offer', models.BooleanField()),
                ('rate', models.CharField(max_length=5)),
                ('warranty', models.CharField(blank=True, max_length=100, null=True)),
                ('connector_size', models.CharField(blank=True, max_length=15, null=True)),
                ('driver_size', models.CharField(blank=True, max_length=15, null=True)),
                ('with_mic', models.CharField(blank=True, max_length=10, null=True)),
                ('connectivity', models.CharField(blank=True, max_length=30, null=True)),
                ('bluetooth_range', models.CharField(blank=True, max_length=15, null=True)),
                ('charging_time', models.CharField(blank=True, max_length=15, null=True)),
                ('play_time', models.CharField(blank=True, max_length=15, null=True)),
                ('fast_charging', models.CharField(blank=True, max_length=50, null=True)),
                ('designed_for', models.CharField(blank=True, max_length=50, null=True)),
                ('connector_type', models.CharField(blank=True, max_length=50, null=True)),
                ('cable_included', models.CharField(blank=True, max_length=50, null=True)),
                ('output_current', models.CharField(blank=True, max_length=50, null=True)),
                ('number_of_connector', models.CharField(blank=True, max_length=50, null=True)),
                ('material', models.CharField(blank=True, max_length=15, null=True)),
                ('flexible', models.CharField(blank=True, max_length=15, null=True)),
                ('compatible_brand', models.CharField(blank=True, max_length=30, null=True)),
                ('compatible_model', models.CharField(blank=True, max_length=50, null=True)),
                ('capacity', models.CharField(blank=True, max_length=30, null=True)),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.camera')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.category')),
                ('display', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.display')),
                ('img', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.image')),
                ('memory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.memory')),
                ('other_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.otherdetail')),
                ('processor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.processor')),
                ('subcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.subcategory')),
            ],
        ),
        migrations.AddField(
            model_name='memory',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.subcategory'),
        ),
        migrations.AddField(
            model_name='image',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.subcategory'),
        ),
        migrations.AddField(
            model_name='display',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.subcategory'),
        ),
        migrations.AddField(
            model_name='camera',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.subcategory'),
        ),
    ]
