# Generated by Django 3.1.5 on 2021-06-27 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('cart', '0002_myorder'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyOrder',
            new_name='PlacedOrder',
        ),
    ]
