# Generated by Django 3.1.5 on 2021-06-29 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20210627_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryaddress',
            name='order',
        ),
        migrations.AddField(
            model_name='orderitems',
            name='order_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.deliveryaddress'),
        ),
    ]
